### ISSUE TITLE
GDB has no way of dereferencing WASM pointers 

### ISSUE THREAD

**Issue by rianhunter** [yurydelendik/webassembly-dwarf#13]
This issue does not pertain to correctly generating DWARF "Location Descriptions." That is possible with the current arrangement.

The issue is when dereferencing pointers on the GDB console. Say you have an "int *foo". GDB can correctly do "print foo" but it cannot do "print *foo."

Is there a way to communicate to GDB how to dereference pointer types in DWARF? I say GDB here but I suspect this also applies to LLDB.

**Comment by yurydelendik** [comment]
At this moment deferencing of points is happening at DWARF level using `DW_OP_deref` and other similar operations -- not different from native platforms. With multi-memory proposal, we need to resolve #10.

There are two ways GDB/LLDB can work with:
1. directly with WebAssembly runtime; in this case deref will just work, but it is not implemented yet AFAIK, see e.g. https://reviews.llvm.org/D78801.
2. with transformed DWARF coming from JIT/AOT compiler; it is more complicated, has limitations and might be confusing. For example, in wasmtime project, we just convert references/pointers into special structures with utility functions to unwrap them (see https://github.com/bytecodealliance/wasmtime/pull/1482).

**Comment by rianhunter** [comment]
Your second point is to what I was referring. Thank you for the reference, while that requires transforming debug-level pointer types that is a sufficient solution. Thank you
