### ISSUE TITLE
Add documentation on Location Descriptions

### ISSUE THREAD

**Issue by rianhunter** [yurydelendik/webassembly-dwarf#14]
WASM location descriptions which reference stack variables are usually of the form "DW_OP_plus_uconst <OFFSET>" This is not valid DWARF and was confusing upon discovery. It would be helpful if there was a blurb in this standard about the form of stack variable locations.

**Comment by yurydelendik** [comment]
Can you define term "stack variables"? I don't understand analogy with`DW_OP_plus_uconst`, but it may still can be used when declaring variables in DWARF.

Latest I found `DW_OP_fbreg` is used instead (even in native code), e.g.

```
0x00000026:   DW_TAG_subprogram
                DW_AT_low_pc	(0x0000000000000003)
                DW_AT_high_pc	(0x00000000000000ce)
                DW_AT_frame_base	(DW_OP_WASM_location 0x0 +3, DW_OP_stack_value)
                DW_AT_name	("fib")
                DW_AT_decl_file	("./fib-wasm.c")
                DW_AT_decl_line	(8)
                DW_AT_prototyped	(true)
                DW_AT_type	(0x0000008f "int")
                DW_AT_external	(true)

0x0000003e:     DW_TAG_formal_parameter
                  DW_AT_location	(DW_OP_fbreg +28)
                  DW_AT_name	("n")
                  DW_AT_decl_file	("./fib-wasm.c")
                  DW_AT_decl_line	(8)
                  DW_AT_type	(0x0000008f "int")

0x0000004c:     DW_TAG_variable
                  DW_AT_location	(DW_OP_fbreg +24)
                  DW_AT_name	("t")
                  DW_AT_decl_file	("./fib-wasm.c")
                  DW_AT_decl_line	(9)
                  DW_AT_type	(0x0000008f "int")

...
```

**Comment by rianhunter** [comment]
By "stack variables" I mean auto variables in C.

I am using Clang/LLVM 10. DW_AT_location is only emitted with (`DW_OP_plus_uconst CONSTANT`). What version prefixes with `DW_OP_fbreg`?

**Comment by yurydelendik** [comment]
> What version prefixes with DW_OP_fbreg?
 
The non-clarity/deficiency of `DW_OP_plus_uconst` was addressed somewhere between versions 10 and 11.

```
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 1090a830692a863ccb091e3fad8cc1a287417493)
Target: wasm32-unknown-wasi
```

**Comment by rianhunter** [comment]
Thanks I was looking for clarification on this, maybe this issue still pertains if you wish to accommodate users running older versions of Clang 10 while they are still widespread. Feel free to close if not.

**Comment by yurydelendik** [comment]
The stack variables with `DW_OP_plus_uconst` was an experimental, so it does not need to be documented. `DW_OP_fbreg` is used in native platforms, so it does not need addition documentation. Closing as answered.
