### ISSUE TITLE
Ordering of sections

### ISSUE THREAD

**Issue by Jiboo** [yurydelendik/webassembly-dwarf#6]
Hello,

Because of dependencies in dwarf sections, maybe the spec should define an order for them, for example `.debug_str` and `.debug_abbrev` should appear in the module before `.debug_info`?

Also, I know that it would increase start-up time, although in my opinion, it would be more convenient to have `.debug_*` (or `external_debug_info`) custom sections before the `code` section.
If it stays after, you'd have to wait to download the full code section and not generate any code in the meantime before realizing if you should generate debug info alongside the code. If there are indeed debug infos, you'll have to finish download all the debug sections before being able to generate code with debug infos.

Bye,
JB.

**Comment by yurydelendik** [comment]
> Because of dependencies in dwarf sections, maybe the spec should define an order for them, for example .debug_str and .debug_abbrev should appear in the module before .debug_info?

The efficient section order depends on debug info consumers use cases. And best way to identify the .debug_* section order is to outline the possible use cases. Though I'm not sure the ordering has to be mandatory, it needs to be a recommendation to improve the consumers performance.

For example, .debug_info references all other .debug_* sections, placing it at the end of the file. Though, as you mentioned, for resolving inlined calls stack trace, it is enough to have .debug_str and .debug_abbrev, .debug_aranges and .debug_info. It is not enough to set a breakpoint, for that you will additionally need .debug_line and maybe .debug_line_str.

**Comment by Jiboo** [comment]
I'm using LLVM to generate IR from wasm, in a similar way to WAVM.

If I understood the spec correctly, JIT should somehow adapt the wasm dwarf to native dwarf that they may attach to the emitted native code.

I'm not completely familiar with LLVM or dwarf,, and not sure if this is possible withe the LLVM C API, and I though I'd just parse the dwarf sections, and use a DIBuilder to attach compilationUnit, subProgram and debugLocation metadata to my LLVM IR (if I somehow get this to work maybe I'll add support for more dwarf features: blocks, namespaces, variables..). That's why I'd rather have the debug sections in dependency order and before the code section.

Let's forget about my potential use case, and discuss the more serious implementation that would achieve converting the wasm dwarf data to native dwarf, as the spec advise.
If they start streaming the codegen while downloading the wasm code section, they probably would need to map wasm PC/instructions to native PC/instructions, to update the dwarf sections when they are finished downloading, and as there is no way to know which wasm instructions will have debug_line infos, this map should have an entry for each instruction in the wasm code section. And they would have to do this wether or not the file has debug infos, as they wouldn't know if the module has debug infos before finishing downloading the code section. Having the debug sections before the code would remove the need for that map.

**Comment by yurydelendik** [comment]
> If I understood the spec correctly, JIT should somehow adapt the wasm dwarf to native dwarf that they may attach to the emitted native code.

That's correct. The transformation process will require all dwarf sections to be loaded and will require knowing wasm instruction to PC instructions transform for some or entire code section. I'll try to remove some assumptions that were made in the comment above, and here is what I found out so far:

- `.debug_line` entries may have a different order than the original wasm section;
- `.debug_info` is needed for a native debugger to operate and refers all other dwarf section (See Appendix B. Debug Section Relationships of the DWARF standard);
- `.debug_loc`, `.debug_ranges`, and attributes in DIEs of `.debug_info` will be adjusted based on address transforms and Wasm specific locations;
- native DWARF data for JIT generated functions can be [changed/registered](https://sourceware.org/gdb/current/onlinedocs/gdb/JIT-Interface.html#JIT-Interface) with native debugger at any time;
- it is possible to have multiple compilations of the same function and do it for part of the wasm code.

Not sure if this addresses or changes your concerns above. For this document creation, I'm trying to stay away from any specific JIT/AOT compiler implementation and DWARF read/write libraries to express what need to be done to make native debugger usable.

FWIW I'm using [wasmtime](https://github.com/CraneStation/wasmtime) as a playground to experiment with the transformation (see [fork's debug_line branch](https://github.com/yurydelendik/wasmtime/tree/debug_line) for AOT logic, and I'm working on JIT pilot atm).

**Comment by yurydelendik** [comment]
> That's why I'd rather have the debug sections in dependency order and before the code section.

As I understand, you are asking for a "flag" in the wasm file itself, that will be explicitly documented here, that will force compiler to switch into debug generation mode, instead of having compiler to decide to select this mode depending if debugger is attached or not.

> If they start streaming the codegen while downloading the wasm code section...

So question is: does it make sense to generate native code and its debug info for portion of the code section (e.g. single function)? Yes, it does, and having DWARF section before code section will make it faster in this case. It is also true, that it will bring a burden on "no-debugger attached" use cases, since compiler have to wait/skip unneeded sections. The different question is: does it make sense to enforce this section order at spec level and assume that all JIT/AOT compilers will generate native code using streaming approach you described?

**Comment by Jiboo** [comment]
> * native DWARF data for JIT generated functions can be [changed/registered](https://sourceware.org/gdb/current/onlinedocs/gdb/JIT-Interface.html#JIT-Interface) with native debugger at any time;

That's an interesting path to investigate, I'll read into that, thanks.

> As I understand, you are asking for a "flag" in the wasm file itself,

No, I tried to find arguments for placing the debug sections before the code section.

> So question is: does it make sense to generate native code and its debug info for portion of the code section (e.g. single function)?

Not really what I tried to implied, sorry that I wasn't clear enough.

I'm gonna close this, thank you for your time.
