### ISSUE TITLE
LLVM implementation?

### ISSUE THREAD

**Issue by justinclift** [yurydelendik/webassembly-dwarf#7]
With the DWARF sections currently generated by LLVM (v8, and development) for wasm, are they following this spec?

Asking because I'm writing some initial parsing code for the `.debug_*` sections in wasm files.

Will soon be up to figuring out how locations are handled (eg locals, heap, etc), and this spec seems to be the desired approach.

Just not sure if it's been implemented (even experimentally) yet. :wink:

**Comment by yurydelendik** [comment]
> With the DWARF sections currently generated by LLVM (v8, and development) for wasm, are they following this spec?

The location expression [patch](https://reviews.llvm.org/D52634) is not landed or reviewed yet -- that only affects wasm specific locations, such as wasm locals/params. The rest of the DWARF sections data, including simple constant expressions, are emitted per this spec in the LLVM.

The llvm-dwarfdump can inspect the wasm file sections. There is also https://github.com/yurydelendik/dwarf-to-json project (which is used at https://wasdk.github.io/wasmcodeexplorer/ and Firefox).

I'm not sure about the timeline of [D52634](https://reviews.llvm.org/D52634) or another WIP patch landings. These patches are already [present](https://github.com/rust-lang/llvm-project/pull/2) in Rust nightly. See also https://github.com/yurydelendik/llvm-project/tree/frame-pointer .

Closing the issue as answered. If you have further questions on the subject please continue the thread or contact me on IRC.

**Comment by justinclift** [comment]
Fantastic, thanks heaps @yurydelendik I'll grab the patches from your `frame-pointer` branch, and apply them to the [`release_80`](https://github.com/justinclift/llvm/tree/release_80-wasm_v2) branch I'm working with.  It's just a snapshot from yesterday, but has some other pieces in it I'm wanting. :smile:

Btw, that "WebAssembly Code Explorer" should be really useful for people wanting to understand the bitcode format. :smile:

Wish I'd realised it exists a few weeks ago, when first looking into that part of things. :wink:

**Comment by justinclift** [comment]
Hmmm, is this correct:

https://github.com/yurydelendik/llvm-project/blob/31859102016e952426b935536611bda7ded9c768/llvm/lib/Target/WebAssembly/WebAssemblyExplicitLocals.cpp#L388-L393

Just asking because I'm not used to seeing braces `{}` without a control structure associated with them (`for`, `if`, etc)

**Comment by yurydelendik** [comment]
> is this correct

I just put emphasis on WIP block of code I was planning to refactor or improve. The code is correct.

**Comment by justinclift** [comment]
No worries. :smile:
